/**
 * @fileOverview Definition of all reducer actions.
 */

export const SERVER_TIMESTAMP_UPDATE = 'SERVER_TIMESTAMP_UPDATE';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const UPDATE_POST_VALUE = 'UPDATE_POST_VALUE';
export const CREATE_POST = 'CREATE_POST';
export const FETCH_POST_DETAILS_SUCCESS = 'FETCH_POST_DETAILS_SUCCESS';
